# Generated by Django 4.1.9 on 2023-06-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
