version: '3.9'
services:
  api:
    build:
      context: ./service
      dockerfile: ./Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./service:/code
    ports:
      - 8000:8000
    env_file:
      - .env
