# Generated by Django 4.1.9 on 2023-06-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
